AirlinesMvcApp/Controllers/FlightController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
//using AirlinesLibrary.Models;
//using AirlinesLibrary.Repos;
using EFAirlinesLibrary.Models;
using EFAirlinesLibrary.Repos;
namespace AirlinesMvcApp.Controllers {
    public class FlightController : Controller {
        static HttpClient client = new HttpClient() { BaseAddress = new Uri("http://localhost:5071/api/Flight/") };
        public async Task<ActionResult> Index() {
            List<Flight> flights = await client.GetFromJsonAsync<List<Flight>>("");
            return View(flights);
        }
        public async Task<ActionResult> Details(string fno) {
            Flight flight = await client.GetFromJsonAsync<Flight>("" + fno);
            return View(flight);
        }
        public ActionResult Create() {
            Flight flight = new Flight();
            return View(flight);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Flight flight) {
            await client.PostAsJsonAsync<Flight>("", flight);
            return RedirectToAction(nameof(Index));
        }
        [Route("Flight/Edit/{fno}")]
        public async Task<ActionResult> Edit(string fno) {
            Flight flight = await client.GetFromJsonAsync<Flight>("" + fno);
            return View(flight);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Flight/Edit/{fno}")]
        public async Task<ActionResult> Edit(string fno, Flight flight) {
            await client.PutAsJsonAsync<Flight>("" + fno, flight);
            return RedirectToAction(nameof(Index));
        }
        [Route("Flight/Delete/{fno}")]
        public async Task<ActionResult> Delete(string fno) {
            Flight flight = await client.GetFromJsonAsync<Flight>("" + fno);
            return View(flight);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Flight/Delete/{fno}")]
        public async Task<ActionResult> Delete(string fno, IFormCollection collection) {
            await client.DeleteAsync("" + fno);
            return RedirectToAction(nameof(Index));
        }
    }
}

AirlinesMvcApp/Controllers/FlightScheduleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
//using AirlinesLibrary.Models;
//using AirlinesLibrary.Repos;
using Microsoft.AspNetCore.Mvc.Rendering;
using EFAirlinesLibrary.Models;
using EFAirlinesLibrary.Repos;

namespace AirlinesMvcApp.Controllers {
    public class FlightScheduleController : Controller {
        static HttpClient client = new HttpClient() { BaseAddress = new Uri("http://localhost:5071/api/FlightSchedule/") };
        public async Task<ActionResult> Index() {
            List<FlightSchedule> schedules = await client.GetFromJsonAsync<List<FlightSchedule>>("");
            return View(schedules);
        }
        public async Task<ActionResult> Details(string fno, DateTime trdate) {
            FlightSchedule schedule = await client.GetFromJsonAsync<FlightSchedule>("" + fno + "/" + trdate.ToLongDateString());
            return View(schedule);
        }
        public ActionResult Create() {
            FlightSchedule schedule = new FlightSchedule();
            return View(schedule);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FlightSchedule schedule) {
            await client.PostAsJsonAsync<FlightSchedule>("", schedule);
            return RedirectToAction(nameof(Index));
        }
        [Route("FlightSchedule/Edit/{fno}/{trdate}")]
        public async Task<ActionResult> Edit(string fno, DateTime trdate) {
            FlightSchedule schedule = await client.GetFromJsonAsync<FlightSchedule>("" + fno + "/" + trdate.ToLongDateString());
            return View(schedule);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("FlightSchedule/Edit/{fno}/{trdate}")]
        public async Task<ActionResult> Edit(string fno, DateTime trdate, FlightSchedule schedule) {
            await client.PutAsJsonAsync<FlightSchedule>("" + fno + "/" + trdate, schedule);
            return RedirectToAction(nameof(Index));
        }
        [Route("FlightSchedule/Delete/{fno}/{trdate}")]
        public async Task<ActionResult> Delete(string fno, DateTime trdate) {
            FlightSchedule schedule = await client.GetFromJsonAsync<FlightSchedule>("" + fno + "/" + trdate.ToLongDateString());
            return View(schedule);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("FlightSchedule/Delete/{fno}/{trdate}")]
        public async Task<ActionResult> Delete(string fno, DateTime trdate, IFormCollection collection) {
            await client.DeleteAsync("" + fno + "/" + trdate);
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> SchedulesByFlight(string fno) {
            List<FlightSchedule> schedules = await client.GetFromJsonAsync<List<FlightSchedule>>("" + "ByFlight/" + fno);
            return View(schedules);
        }
        public async Task<ActionResult> SchedulesByDate(DateTime trdate) {
            List<FlightSchedule> schedules = await client.GetFromJsonAsync<List<FlightSchedule>>("" + "ByDate/" + trdate);
            return View(schedules);
        }
    }
}

AirlinesMvcApp/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
//using AirlinesLibrary.Models;
//using AirlinesLibrary.Repos;
using EFAirlinesLibrary.Models;
using EFAirlinesLibrary.Repos;
using NuGet.ProjectModel;

namespace AirlinesMvcApp.Controllers {
    public class ReservationController : Controller {
        static HttpClient client = new HttpClient() { BaseAddress = new Uri("http://localhost:5071/api/Reservation/") };
        public async Task<ActionResult> Index() {
            List<ReservationMaster> masters = await client.GetFromJsonAsync<List<ReservationMaster>>("");
            return View(masters);
        }
        public async Task<ActionResult> Details(string pnr) {
            ReservationMaster master = await client.GetFromJsonAsync<ReservationMaster>("" + pnr);
            return View(master);
        }
        public ActionResult Create() {
            ReservationMaster master = new ReservationMaster();
            return View(master);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ReservationMaster master) {
            master.NoOfPassengers = 0;
            await client.PostAsJsonAsync<ReservationMaster>("", master);
            return RedirectToAction(nameof(Index));
        }
        [Route("Reservation/Edit/{pnr}")]
        public async Task<ActionResult> Edit(string pnr) {
            ReservationMaster master = await client.GetFromJsonAsync<ReservationMaster>("" + pnr);
            return View(master);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Reservation/Edit/{pnr}")]
        public async Task<ActionResult> Edit(string pnr, ReservationMaster master) {
            await client.PutAsJsonAsync<ReservationMaster>("" + pnr, master);
            return RedirectToAction(nameof(Index));
        }
        [Route("Reservation/Delete/{pnr}")]
        public async Task<ActionResult> Delete(string pnr) {
            ReservationMaster master = await client.GetFromJsonAsync<ReservationMaster>("" + pnr);
            return View(master);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Reservation/Delete/{pnr}")]
        public async Task<ActionResult> Delete(string pnr, IFormCollection collection) {
            await client.DeleteAsync("" + pnr);
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> ReservationsByFlight(string fno) {
            List<ReservationMaster> masters = await client.GetFromJsonAsync<List<ReservationMaster>>("" + "ByFlight/" + fno);
            return View(masters);
        }
        public async Task<ActionResult> ReservationsByDate(DateTime trdate) {
            List<ReservationMaster> masters = await client.GetFromJsonAsync<List<ReservationMaster>>("" + "ByDate/" + trdate);
            return View(masters);
        }
        public async Task<ActionResult> ReservationsByFlightAndDate(string fno, DateTime trdate) {
            List<ReservationMaster> masters = await client.GetFromJsonAsync<List<ReservationMaster>>("" + fno + "/" + trdate);
            return View(masters);
        }
        static int passCount;
        // Template: List; Model class: ReservationDetail
        public async Task<ActionResult> Passengers(string pnr) {
            List<ReservationDetail> passengers = new List<ReservationDetail>();
                passengers = await client.GetFromJsonAsync<List<ReservationDetail>>("" + "PassengersByPNR/" + pnr);
            passCount = passengers.Count;
            ViewBag.PNR = pnr;
            return View(passengers);
        }
        // Template: Create; Model class: ReservationDetail
        public ActionResult CreatePassenger(string pnr) {
            ReservationDetail passenger = new ReservationDetail();
            passenger.PNRNo = pnr;
            passenger.PassengerNo = passCount + 1;
            return View(passenger);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreatePassenger(ReservationDetail passenger) {
            await client.PostAsJsonAsync<ReservationDetail>("" + "Passenger", passenger);
            return RedirectToAction(nameof(Passengers), new { pnr = passenger.PNRNo });
        }
        // Template: Details; Model class: ReservationDetail
        public async Task<ActionResult> PassengerDetails(string pnr, int pno) {
            ReservationDetail passenger = await client.GetFromJsonAsync<ReservationDetail>("" + pnr + "/" + pno);
            return View(passenger);
        }
        // Template: Edit; Model class: ReservationDetail
        [Route("Reservation/EditPassenger/{pnr}/{pno}")]
        public async Task<ActionResult> EditPassenger(string pnr, int pno) {
            ReservationDetail passenger = await client.GetFromJsonAsync<ReservationDetail>("" + pnr + "/" + pno); return View(passenger);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Reservation/EditPassenger/{pnr}/{pno}")]
        public async Task<ActionResult> EditPassenger(string pnr, int pno, ReservationDetail detail){
            await client.PutAsJsonAsync<ReservationDetail>("" + pnr + "/" + pno, detail);
            return RedirectToAction(nameof(Passengers), new { pnr = pnr });
        }
        // Template: Delete; Model class: ReservationDetail
        [Route("Reservation/DeletePassenger/{pnr}/{pno}")]
        public async Task<ActionResult> DeletePassenger(string pnr, int pno) {
            ReservationDetail passenger = await client.GetFromJsonAsync<ReservationDetail>("" + pnr + "/" + pno); return View(passenger);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Reservation/DeletePassenger/{pnr}/{pno}")]
        public async Task<ActionResult> DeletePassenger(string pnr, int pno, IFormCollection collection) {
            await client.DeleteAsync("" + pnr + "/" + pno);
            return RedirectToAction(nameof(Passengers), new { pnr = pnr });
        }
    }
}

AirlinesMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AirlinesMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AirlinesMvcApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AirlinesMvcApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Flight</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FlightSchedule" asp-action="Index">Flight Schedule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AirlinesMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>